/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <BaseRenderers.h>
#include <RemoteConnector.h>
#include "SerialTransport.h"
#include <IoAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TcMenuRemoteServer remoteServer;
extern NoRenderer renderer;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern BackMenuItem menuBackAdjust;
extern SubMenuItem menuAdjust;
extern AnalogMenuItem menuRCServoStart;
extern BackMenuItem menuBackLimits;
extern SubMenuItem menuLimits;
extern EnumMenuItem menuInputType;
extern BackMenuItem menuBackM1S1;
extern SubMenuItem menuM1S1;
extern BackMenuItem menuBackWizard;
extern SubMenuItem menuWizard;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuWizard; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION


#endif // MENU_GENERATED_CODE_H
